# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - npm run build
          - cat known_hosts >> ~/.ssh/known_hosts
          - ls
          - scp -r build "ubuntu@ec2-18-189-178-202.us-east-2.compute.amazonaws.com:"
          - ssh ubuntu@ec2-18-189-178-202.us-east-2.compute.amazonaws.com "sudo rm -rf /var/www/html/*"
          - ssh ubuntu@ec2-18-189-178-202.us-east-2.compute.amazonaws.com "sudo mv build/* /var/www/html"
        artifacts:
          - build/**